# Generated by Django 5.0.4 on 2024-04-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALSApp', '0003_rename_course_tile_course_course_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_slide',
            field=models.FileField(upload_to='slides/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_video',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
