# Generated by Django 5.0.4 on 2024-04-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALSApp', '0004_alter_course_course_slide_alter_course_course_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_banner',
            field=models.FileField(default=1, upload_to='banner/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course_description',
            field=models.TextField(default=1, max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
